# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------

name: e2e-upgrade
description: 'End-to-End tests for upgrading to new version'

inputs:
  cluster-config-data:
    description: 'The configuration of the underlying cluster (if cluster-type is custom)'
    required: false

runs:
  using: "composite"

  steps:
  - id: prepare-env
    name: Prepare Test Environment
    uses: ./.github/actions/kamel-prepare-env

  - id: configure-cluster
    name: Configure Cluster
    uses: ./.github/actions/kamel-config-cluster
    with:
      cluster-type: ${{ env.TEST_CLUSTER }}
      cluster-config-data: ${{ inputs.cluster-config-data }}
      require-olm: true

  - name: Get Released Kamel CLI
    shell: bash
    run: |
      export KAMEL_VERSION=$(make get-last-released-version)
      curl -L https://github.com/apache/camel-k/releases/download/v${KAMEL_VERSION}/camel-k-client-${KAMEL_VERSION}-linux-64bit.tar.gz -o /tmp/kamel.tar.gz
      pushd /tmp && tar -zxf kamel.tar.gz && popd > /dev/null
      if [ ! -x /tmp/kamel ]; then
        echo "Error: No ${KAMEL_VERSION} downloaded correctly"
        exit 1
      fi

      #
      # Note: cannot use GITHUB_ENV vars in same script as it was defined
      #
      export RELEASED_KAMEL_BINARY=/tmp/kamel-${KAMEL_VERSION}
      mv /tmp/kamel ${RELEASED_KAMEL_BINARY}
      if [ $? == 0 ]; then
        echo "Info: Kamel version installed: $(${RELEASED_KAMEL_BINARY} version)"
        echo "E2E_UPGRADE_RELEASED_KAMEL_BINARY=${RELEASED_KAMEL_BINARY}" >> $GITHUB_ENV
      else
        echo "Error: Failed to install kamel binary ${KAMEL_VERSION}"
        exit 1
      fi

  - id: build-kamel
    name: Build Kamel
    uses: ./.github/actions/kamel-build
    with:
      image-registry-push-host: ${{ env.CLUSTER_IMAGE_REGISTRY_PUSH_HOST }}
      image-registry-pull-host: ${{ env.CLUSTER_IMAGE_REGISTRY_PULL_HOST }}
      image-namespace: ${{ env.CLUSTER_IMAGE_NAMESPACE }}
      # Builds the bundle if an OLM is available.
      # Since configure-cluster requires OLM then this should be true
      build-bundle: ${{ env.CLUSTER_HAS_OLM }}
      kube-admin-user-ctx: ${{ env.CLUSTER_KUBE_ADMIN_USER_CTX }}

  - name: Run IT
    shell: bash
    run: |
      # Use the last released Kamel CLI
      export RELEASED_KAMEL_BIN=${{ env.E2E_UPGRADE_RELEASED_KAMEL_BINARY }}

      echo "Kamel version: $(${RELEASED_KAMEL_BIN} version)"

      # Configure install options
      export CUSTOM_IMAGE=${{ env.BUILD_BINARY_LOCAL_IMAGE_NAME }}
      export CUSTOM_VERSION=${{ env.BUILD_BINARY_LOCAL_IMAGE_VERSION }}
      export KAMEL_INSTALL_MAVEN_REPOSITORIES=$(make get-staging-repo)
      export KAMEL_INSTALL_REGISTRY=${{ env.CLUSTER_IMAGE_REGISTRY_PULL_HOST }}
      export KAMEL_INSTALL_REGISTRY_INSECURE=${{ env.CLUSTER_IMAGE_REGISTRY_INSECURE }}

      # Despite building a bundle we don't want it installed immediately so no OLM_INDEX_BUNDLE var

      # Configure test options
      export CAMEL_K_PREV_IIB=quay.io/operatorhubio/catalog:latest
      export CAMEL_K_NEW_IIB=${{ env.BUILD_BUNDLE_LOCAL_IMAGE_BUNDLE_INDEX }}
      export KAMEL_K_TEST_RELEASE_VERSION=$(make get-last-released-version)
      export KAMEL_K_TEST_OPERATOR_CURRENT_IMAGE=${CUSTOM_IMAGE}:${CUSTOM_VERSION}

      # Then run integration tests
      make test-upgrade
