# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------

name: kamel-install-global-operator
description: 'Installs the camel-k as a global operator in the specified global namespace'

inputs:
  global-operator-namespace:
    description: "The namespace to install the global operator"
    required: true
  catalog-source-name:
    description: "The name of the bundle catalog (only installed in the cluster if OLM is used)"
    required: false
  catalog-source-namespace:
    description: "The namespace of the bundle catalog (only installed in the cluster if OLM is used)"
    required: false
  image-namespace:
    description: 'Namespace in which the image is stored'
    required: true
  image-registry-host:
    description: 'Location of image registry host'
    required: true
  image-name:
    description: 'Reference of the camel-k image'
    required: true
  image-registry-insecure:
    description: "Whether the registry is insecure"
    required: true
  image-version:
    description: "Reference of the camel-k image version"
    required: true

runs:
  using: "composite"

  steps:
  - id: install-global-operator
    name: Execute Operator Install
    shell: bash
    run: |
      ./.github/actions/kamel-install-global-operator/install-global-operator.sh \
        -b "${{ inputs.catalog-source-name }}" \
        -c "${{ inputs.catalog-source-namespace }}" \
        -g "${{ inputs.global-operator-namespace }}" \
        -i "${{ inputs.image-namespace }}" \
        -l "${{ inputs.image-registry-host }}" \
        -n "${{ inputs.image-name }}" \
        -q "${{ env.CAMEL_K_LOG_LEVEL }}" \
        -s "${{ inputs.image-registry-insecure }}" \
        -v "${{ inputs.image-version }}"
