apiVersion: v1
kind: Service
metadata:
  name: my-amqp-service
  labels:
    ActiveMQArtemis: my-amqp
    application: my-amqp-app
spec:
  ports:
    - port: 5672
      name: amqp
    - port: 8161
      name: http
  selector:
    ActiveMQArtemis: my-amqp
    application: my-amqp-app
  type: NodePort
  