version: 2
updates:
  - directory: "/"
    open-pull-requests-limit: 5
    package-ecosystem: "gomod"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "github.com/Masterminds/semver"
      - dependency-name: "github.com/container-tools/spectrum"
      - dependency-name: "github.com/fatih/structs"
      - dependency-name: "github.com/gertd/go-pluralize"
      - dependency-name: "github.com/go-logr/logr"
      - dependency-name: "github.com/golangplus/testing"
      - dependency-name: "github.com/google/go-github/v32"
      - dependency-name: "github.com/google/uuid"
      - dependency-name: "github.com/jpillora/backoff"
      - dependency-name: "github.com/magiconair/properties"
      - dependency-name: "github.com/mitchellh/go-homedir"
      - dependency-name: "github.com/mitchellh/mapstructure"
      - dependency-name: "github.com/onsi/gomega"
      - dependency-name: "github.com/operator-framework/api"
      - dependency-name: "github.com/pkg/errors"
      - dependency-name: "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring"
      - dependency-name: "github.com/prometheus/client_golang"
      - dependency-name: "github.com/prometheus/client_model"
      - dependency-name: "github.com/prometheus/common"
      - dependency-name: "github.com/radovskyb/watcher"
      - dependency-name: "github.com/redhat-developer/service-binding-operator"
      - dependency-name: "github.com/rs/xid"
      - dependency-name: "github.com/scylladb/go-set"
      - dependency-name: "github.com/shurcooL/httpfs"
      - dependency-name: "github.com/shurcooL/vfsgen"
      - dependency-name: "github.com/sirupsen/logrus"
      - dependency-name: "github.com/spf13/cobra"
      - dependency-name: "github.com/spf13/pflag"
      - dependency-name: "github.com/spf13/viper"
      - dependency-name: "github.com/stoewer/go-strcase"
      - dependency-name: "github.com/stretchr/testify"
      - dependency-name: "go.uber.org/multierr"
      - dependency-name: "go.uber.org/zap"
      - dependency-name: "golang.org/x/oauth2"
      - dependency-name: "gopkg.in/inf.v0"
      - dependency-name: "gopkg.in/yaml.v2"
