daysUntilStale: 90
daysUntilClose: 15
exemptLabels:
  - status/never-stale
staleLabel: status/stale
markComment: >
  This issue has been automatically marked as stale due to 90 days of inactivity. 
  It will be closed if no further activity occurs within 15 days.
  If you think that’s incorrect or the issue should never stale, please simply write any comment.
  Thanks for your contributions!
closeComment: false
only: issues