# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------

name: kamel-install
description: 'Execute kamel to install the Camel K operator'

inputs:
  kube-admin-user-ctx:
    description: "The administration user context of the cluster"
    required: true
  build-catalog-source:
    description: "The name of the bundle catalog (only installed in the cluster if OLM is used)"
    required: false
  image-namespace:
    description: 'Namespace in which the image is stored'
    required: true
  image-registry-host:
    description: 'Location of image registry host'
    required: true
  image-name:
    description: 'Reference of the camel-k image'
    required: true
  image-registry-insecure:
    description: "Whether the registry is insecure"
    required: true
  image-version:
    description: "Reference of the camel-k image version"
    required: true

runs:
  using: "composite"
  steps:
    - id: execute-kamel
      name: Install Camel K
      shell: bash
      run: |
        ./.github/actions/kamel-install/install.sh \
          -a "${{ inputs.kube-admin-user-ctx }}" \
          -c "${{ inputs.build-catalog-source }}" \
          -i "${{ inputs.image-namespace }}" \
          -l "${{ inputs.image-registry-host }}" \
          -n "${{ inputs.image-name }}" \
          -s "${{ inputs.image-registry-insecure }}" \
          -v "${{ inputs.image-version }}"

    - id: post-execution
      shell: bash
      run: |
        rm -f /tmp/config
        export -n KUBECONFIG
