linters-settings:
  lll:
    line-length: 170
linters:
  enable-all: true
  disable:
    - dupl
    - gochecknoinits
    - gochecknoglobals
    - funlen
    - godox
    - whitespace
    - gocognit
    - wsl
