# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

# Align K8S resources to operator-sdk
[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

# Align controller-runtime to operator-sdk
[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.1.10"

# Override prometheus client to match version required by controller-runtime
[[override]]
  name = "github.com/prometheus/client_golang"
  version = "=0.9.0"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  # branch = "master" #osdk_branch_annotation
  version = "=v0.5.0" #osdk_version_annotation

[[constraint]]
  name = "github.com/coreos/prometheus-operator"
  version = "0.27.0"

[[constraint]]
  name = "github.com/knative/eventing"
  version = "0.3.0"

[prune]
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false
