apiVersion: v1
kind: Secret
metadata:
  name: secret-specific
  labels:
    camel.apache.org/kamelet: timer-source
    camel.apache.org/kamelet.configuration: specific
type: Opaque
data:
  # camel.kamelet.timer-source.specific.message=specific
  application.properties: Y2FtZWwua2FtZWxldC50aW1lci1zb3VyY2Uuc3BlY2lmaWMubWVzc2FnZT1zcGVjaWZpYwo=
