apiVersion: v1
kind: Secret
metadata:
  name: secret-default
  labels:
    camel.apache.org/kamelet: timer-source
type: Opaque
data:
  # camel.kamelet.timer-source.message=default
  application.properties: Y2FtZWwua2FtZWxldC50aW1lci1zb3VyY2UubWVzc2FnZT1kZWZhdWx0Cg==
