/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// CamelArtifactDependencyApplyConfiguration represents a declarative configuration of the CamelArtifactDependency type for use
// with apply.
//
// CamelArtifactDependency represent a maven's dependency.
type CamelArtifactDependencyApplyConfiguration struct {
	// the maven dependency
	MavenArtifactApplyConfiguration `json:",inline"`
	// provide a list of artifacts to exclude for this dependency
	Exclusions []CamelArtifactExclusionApplyConfiguration `json:"exclusions,omitempty"`
}

// CamelArtifactDependencyApplyConfiguration constructs a declarative configuration of the CamelArtifactDependency type for use with
// apply.
func CamelArtifactDependency() *CamelArtifactDependencyApplyConfiguration {
	return &CamelArtifactDependencyApplyConfiguration{}
}

// WithGroupID sets the GroupID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupID field is set to the value of the last call.
func (b *CamelArtifactDependencyApplyConfiguration) WithGroupID(value string) *CamelArtifactDependencyApplyConfiguration {
	b.MavenArtifactApplyConfiguration.GroupID = &value
	return b
}

// WithArtifactID sets the ArtifactID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ArtifactID field is set to the value of the last call.
func (b *CamelArtifactDependencyApplyConfiguration) WithArtifactID(value string) *CamelArtifactDependencyApplyConfiguration {
	b.MavenArtifactApplyConfiguration.ArtifactID = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *CamelArtifactDependencyApplyConfiguration) WithType(value string) *CamelArtifactDependencyApplyConfiguration {
	b.MavenArtifactApplyConfiguration.Type = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *CamelArtifactDependencyApplyConfiguration) WithVersion(value string) *CamelArtifactDependencyApplyConfiguration {
	b.MavenArtifactApplyConfiguration.Version = &value
	return b
}

// WithClassifier sets the Classifier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Classifier field is set to the value of the last call.
func (b *CamelArtifactDependencyApplyConfiguration) WithClassifier(value string) *CamelArtifactDependencyApplyConfiguration {
	b.MavenArtifactApplyConfiguration.Classifier = &value
	return b
}

// WithExclusions adds the given value to the Exclusions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Exclusions field.
func (b *CamelArtifactDependencyApplyConfiguration) WithExclusions(values ...*CamelArtifactExclusionApplyConfiguration) *CamelArtifactDependencyApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExclusions")
		}
		b.Exclusions = append(b.Exclusions, *values[i])
	}
	return b
}
