/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// GitConfigSpecApplyConfiguration represents a declarative configuration of the GitConfigSpec type for use
// with apply.
type GitConfigSpecApplyConfiguration struct {
	URL    *string `json:"url,omitempty"`
	Secret *string `json:"secret,omitempty"`
	Branch *string `json:"branch,omitempty"`
	Tag    *string `json:"tag,omitempty"`
	Commit *string `json:"commit,omitempty"`
}

// GitConfigSpecApplyConfiguration constructs a declarative configuration of the GitConfigSpec type for use with
// apply.
func GitConfigSpec() *GitConfigSpecApplyConfiguration {
	return &GitConfigSpecApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *GitConfigSpecApplyConfiguration) WithURL(value string) *GitConfigSpecApplyConfiguration {
	b.URL = &value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *GitConfigSpecApplyConfiguration) WithSecret(value string) *GitConfigSpecApplyConfiguration {
	b.Secret = &value
	return b
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *GitConfigSpecApplyConfiguration) WithBranch(value string) *GitConfigSpecApplyConfiguration {
	b.Branch = &value
	return b
}

// WithTag sets the Tag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tag field is set to the value of the last call.
func (b *GitConfigSpecApplyConfiguration) WithTag(value string) *GitConfigSpecApplyConfiguration {
	b.Tag = &value
	return b
}

// WithCommit sets the Commit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Commit field is set to the value of the last call.
func (b *GitConfigSpecApplyConfiguration) WithCommit(value string) *GitConfigSpecApplyConfiguration {
	b.Commit = &value
	return b
}
