/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// HeaderSpecApplyConfiguration represents an declarative configuration of the HeaderSpec type for use
// with apply.
type HeaderSpecApplyConfiguration struct {
	Type        *string `json:"type,omitempty"`
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Required    *bool   `json:"required,omitempty"`
	Default     *string `json:"default,omitempty"`
}

// HeaderSpecApplyConfiguration constructs an declarative configuration of the HeaderSpec type for use with
// apply.
func HeaderSpec() *HeaderSpecApplyConfiguration {
	return &HeaderSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *HeaderSpecApplyConfiguration) WithType(value string) *HeaderSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *HeaderSpecApplyConfiguration) WithTitle(value string) *HeaderSpecApplyConfiguration {
	b.Title = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *HeaderSpecApplyConfiguration) WithDescription(value string) *HeaderSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithRequired sets the Required field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Required field is set to the value of the last call.
func (b *HeaderSpecApplyConfiguration) WithRequired(value bool) *HeaderSpecApplyConfiguration {
	b.Required = &value
	return b
}

// WithDefault sets the Default field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Default field is set to the value of the last call.
func (b *HeaderSpecApplyConfiguration) WithDefault(value string) *HeaderSpecApplyConfiguration {
	b.Default = &value
	return b
}
