/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	camelv1 "github.com/apache/camel-k/v2/pkg/apis/camel/v1"
	corev1 "k8s.io/api/core/v1"
)

// IntegrationSpecApplyConfiguration represents a declarative configuration of the IntegrationSpec type for use
// with apply.
//
// IntegrationSpec specifies the configuration of an Integration.
// The Integration will be watched by the operator which will be in charge to run the related application, according to the configuration specified.
type IntegrationSpecApplyConfiguration struct {
	// the number of `Pods` needed for the running Integration
	Replicas *int32 `json:"replicas,omitempty"`
	// the sources which contain the Camel routes to run
	Sources []SourceSpecApplyConfiguration `json:"sources,omitempty"`
	// the configuration of the project to build on Git
	Git *GitConfigSpecApplyConfiguration `json:"git,omitempty"`
	// a source in YAML DSL language which contain the routes to run
	Flows []FlowApplyConfiguration `json:"flows,omitempty"`
	// the reference of the `IntegrationKit` which is used for this Integration
	IntegrationKit *corev1.ObjectReference `json:"integrationKit,omitempty"`
	// the list of Camel or Maven dependencies required by the Integration
	Dependencies []string `json:"dependencies,omitempty"`
	// the profile needed to run this Integration
	Profile *camelv1.TraitProfile `json:"profile,omitempty"`
	// the traits needed to run this Integration
	Traits *TraitsApplyConfiguration `json:"traits,omitempty"`
	// Pod template customization.
	//
	// Deprecated: use container, init-containers or owner traits instead
	PodTemplate *PodSpecTemplateApplyConfiguration `json:"template,omitempty"`
	// Deprecated:
	//
	// Use camel trait (camel.properties) to manage properties
	// Use mount trait (mount.configs) to manage configs
	// Use mount trait (mount.resources) to manage resources
	// Use mount trait (mount.volumes) to manage volumes
	Configuration []ConfigurationSpecApplyConfiguration `json:"configuration,omitempty"`
	// additional Maven repositories to be used
	Repositories []string `json:"repositories,omitempty"`
	// custom SA to use for the Integration
	ServiceAccountName *string `json:"serviceAccountName,omitempty"`
}

// IntegrationSpecApplyConfiguration constructs a declarative configuration of the IntegrationSpec type for use with
// apply.
func IntegrationSpec() *IntegrationSpecApplyConfiguration {
	return &IntegrationSpecApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *IntegrationSpecApplyConfiguration) WithReplicas(value int32) *IntegrationSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithSources adds the given value to the Sources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Sources field.
func (b *IntegrationSpecApplyConfiguration) WithSources(values ...*SourceSpecApplyConfiguration) *IntegrationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSources")
		}
		b.Sources = append(b.Sources, *values[i])
	}
	return b
}

// WithGit sets the Git field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Git field is set to the value of the last call.
func (b *IntegrationSpecApplyConfiguration) WithGit(value *GitConfigSpecApplyConfiguration) *IntegrationSpecApplyConfiguration {
	b.Git = value
	return b
}

// WithFlows adds the given value to the Flows field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Flows field.
func (b *IntegrationSpecApplyConfiguration) WithFlows(values ...*FlowApplyConfiguration) *IntegrationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFlows")
		}
		b.Flows = append(b.Flows, *values[i])
	}
	return b
}

// WithIntegrationKit sets the IntegrationKit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IntegrationKit field is set to the value of the last call.
func (b *IntegrationSpecApplyConfiguration) WithIntegrationKit(value corev1.ObjectReference) *IntegrationSpecApplyConfiguration {
	b.IntegrationKit = &value
	return b
}

// WithDependencies adds the given value to the Dependencies field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Dependencies field.
func (b *IntegrationSpecApplyConfiguration) WithDependencies(values ...string) *IntegrationSpecApplyConfiguration {
	for i := range values {
		b.Dependencies = append(b.Dependencies, values[i])
	}
	return b
}

// WithProfile sets the Profile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Profile field is set to the value of the last call.
func (b *IntegrationSpecApplyConfiguration) WithProfile(value camelv1.TraitProfile) *IntegrationSpecApplyConfiguration {
	b.Profile = &value
	return b
}

// WithTraits sets the Traits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Traits field is set to the value of the last call.
func (b *IntegrationSpecApplyConfiguration) WithTraits(value *TraitsApplyConfiguration) *IntegrationSpecApplyConfiguration {
	b.Traits = value
	return b
}

// WithPodTemplate sets the PodTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplate field is set to the value of the last call.
func (b *IntegrationSpecApplyConfiguration) WithPodTemplate(value *PodSpecTemplateApplyConfiguration) *IntegrationSpecApplyConfiguration {
	b.PodTemplate = value
	return b
}

// WithConfiguration adds the given value to the Configuration field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Configuration field.
func (b *IntegrationSpecApplyConfiguration) WithConfiguration(values ...*ConfigurationSpecApplyConfiguration) *IntegrationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConfiguration")
		}
		b.Configuration = append(b.Configuration, *values[i])
	}
	return b
}

// WithRepositories adds the given value to the Repositories field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Repositories field.
func (b *IntegrationSpecApplyConfiguration) WithRepositories(values ...string) *IntegrationSpecApplyConfiguration {
	for i := range values {
		b.Repositories = append(b.Repositories, values[i])
	}
	return b
}

// WithServiceAccountName sets the ServiceAccountName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountName field is set to the value of the last call.
func (b *IntegrationSpecApplyConfiguration) WithServiceAccountName(value string) *IntegrationSpecApplyConfiguration {
	b.ServiceAccountName = &value
	return b
}
