apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: logger-sink
  label:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "Logger"
    description: "Logs the received payload of each incoming event"
    properties:
      prefix:
        title: Prefix
        description: The prefix to prepend to the logged message
        type: string
        default: "message: "
  types:
    in:
      mediaType: text/plain
    out:
      mediaType: text/plain
  flow:
    from:
      uri: "direct:{{routeId}}"
      steps:
        - log: "{{prefix}}${body}"
