# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------

name: java-builder
description: "Build java modules"
inputs:
  javaVersion:
    description: "Java version"
    required: true
  javaDistribution:
    description: "Java distribution"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.javaVersion }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.javaDistribution }}
        java-version: ${{ inputs.javaVersion }}
    - name: Build java/crds
      working-directory: java/crds
      shell: bash
      run: |
          mvn clean install
    - name: Build java/maven-logging
      working-directory: java/maven-logging
      shell: bash
      run: |
          mvn clean install
