= Running operator as a local process

If you need a finer control on the operator process (ie, attaching a debugger or quickly building and running the operator locally), then you can run and debug the operator binary locally. The idea is that you execute it on your machine and instruct the local process to **watch** a namespace on a Kubernetes cluster (it may be remote or any local environment).

NOTE: if you need a simpler approach you can build and run the operator on a connected cluster (local or remote): see xref:contributing/local-development.adoc[Local development]

Let's use a namespace called `operator-test.

You can start with setting the environment variable `WATCH_NAMESPACE` with the namespace you'd like your operator to watch. You also need to specify the name of the operator, as you may have different operators running on the cluster.
----
export WATCH_NAMESPACE=operator-test
export OPERATOR_ID="camel-k-dev"
----

The next step is to install an `IntegrationPlatform` on the cluster namespace. You probably need to tweak the registry parameters in order to be able to authenticate against an image repository (see below paragraph for local repository instructions). It's important to specify the target operator that will take care of this IntegrationPlatform (`-x` or `--operator-id` option).
----
./kamel install --skip-operator-setup -n operator-test --registry my-registry:5000 -x camel-k-dev
----

Finally, assuming you've built your application correctly we can run the operator:
-----
./kamel operator
-----

Test the local operator by creating a test `Integration`.
-----
./kamel run xyz.abc -n operator-test -x camel-k-dev
-----

IMPORTANT: make sure no other Camel K Operators are watching this namespace, neither you have a global Camel K Operator  installed on your cluster. As you may have more than one Camel K operator installed on the cluster, it's important you specify the `-x` (or `--operator-id`) option.

[[local-minikube]]
== Local operator and local cluster

If you want to run a local operator togheter with ``Minikube`` you will need an additional step in order to let the local operator push images in the local registry. We need to expose the local registry as described in https://minikube.sigs.k8s.io/docs/handbook/registry/#docker-on-windows[this procedure]:

Enable the addon registry (this should be already in place):
----
minikube addons enable registry
----

Get the `Pod` name that is in charge to run the registry and proxy the registry 5000 port to be used locally.
----
kubectl get pods -n kube-system
NAME                               READY   STATUS    RESTARTS   AGE
...
registry-fttbv                     1/1     Running   40         89d
...

kubectl port-forward --namespace kube-system registry-fttbv 5000:5000
----

Update the ``IntegrationPlatform`` to instruct it to use the ``localhost`` registry:
----
./kamel install --skip-operator-setup -n operator-test --registry localhost:5000 --force -x camel-k-dev
----

A similar procedure may work if you use other local environments. The idea is to expose the docker registry and be able to use it from your local operator.

IMPORTANT: using build strategy as `Pod` won't probably work as it will expect the registry to be available at a URL not possible to reach from a local machine.
