apiVersion: v1
kind: Namespace
metadata:
  name: openshift-image-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-registry
  namespace: openshift-image-registry
  labels:
    docker-registry: default
spec:
  replicas: 1
  selector:
    matchLabels:
      docker-registry: default
  template:
    metadata:
      labels:
        docker-registry: default
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: image-registry
  namespace: openshift-image-registry
  labels:
    docker-registry: default
spec:
  selector:
    docker-registry: default
  ports:
  - name: 5000-tcp
    port: 5000
    protocol: TCP
    targetPort: 5000
