# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------

name: kamel-build
description: 'Builds kamel operator image and the bundle'

inputs:
  image-registry-push-host:
    description: 'Location of image registry push host'
    required: false
  image-registry-pull-host:
    description: 'Location of image registry pull host'
    required: false
  image-namespace:
    description: 'Namespace in which to store the image'
    required: false
    default: 'apache'
  make-rules:
    description: 'Override the default make rules'
    required: false
  build-bundle:
    description: 'Build a bundle for install into OLM catalog'
    required: true
    default: false
  catalog-source-namespace:
    description: 'Namespace in which to install the catalog source for the bundle (if required)'
    required: false

runs:
  using: "composite"
  steps:
    - id: build-kamel-binary
      name: Build Kamel Binary
      uses: ./.github/actions/kamel-build-binary
      with:
        image-registry-push-host: ${{ inputs.image-registry-push-host }}
        image-registry-pull-host: ${{ inputs.image-registry-pull-host }}
        image-namespace: ${{ inputs.image-namespace }}
        make-rules: ${{ inputs.make-rules }}

    #
    # By default do not build the image bundle
    #
    - id: build-kamel-bundle
      name: Build Kamel Metadata Bundle
      uses: ./.github/actions/kamel-build-bundle
      if: ${{ inputs.build-bundle == 'true' }}
      with:
        image-registry-push-host: ${{ inputs.image-registry-push-host }}
        image-registry-pull-host: ${{ inputs.image-registry-pull-host }}
        image-namespace: ${{ inputs.image-namespace }}
        local-image-name: ${{ steps.build-kamel-binary.outputs.build-binary-local-image-name }}
        local-image-version: ${{ steps.build-kamel-binary.outputs.build-binary-local-image-version }}
        catalog-source-namespace: ${{ inputs.catalog-source-namespace }}

outputs:
  build-binary-local-image-name:
    description: "Full name of the binary operator image"
    value: ${{ steps.build-kamel-binary.outputs.build-binary-local-image-name }}
  build-binary-local-image-version:
    description: "Version & tag of the binary operator image"
    value: ${{ steps.build-kamel-binary.outputs.build-binary-local-image-version }}
  build-bundle-local-image:
    description: "Full name of the bundle image"
    value: ${{ steps.build-kamel-bundle.outputs.build-bundle-local-image }}
  build-bundle-image-bundle-index:
    description: "Full name of the bundle index image"
    value: ${{ steps.build-kamel-bundle.outputs.build-bundle-image-bundle-index }}
  build-bundle-catalog-source-name:
    description: "Name of the catalog source for the build bundle image"
    value: ${{ steps.build-kamel-bundle.outputs.build-bundle-catalog-source-name }}
