/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apiscamelv1 "github.com/apache/camel-k/v2/pkg/apis/camel/v1"
	versioned "github.com/apache/camel-k/v2/pkg/client/camel/clientset/versioned"
	internalinterfaces "github.com/apache/camel-k/v2/pkg/client/camel/informers/externalversions/internalinterfaces"
	camelv1 "github.com/apache/camel-k/v2/pkg/client/camel/listers/camel/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BuildInformer provides access to a shared informer and lister for
// Builds. Prefer using the type-safe variant (see [TypedBuildInformer]).
type BuildInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() camelv1.BuildLister
}

// TypedBuildInformer provides access to a shared informer and lister for
// Builds, including the type-safe TypedInformer variant.
// It is a superset of BuildInformer.
type TypedBuildInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() BuildIndexInformer
	Lister() camelv1.BuildLister
}

// BuildIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type BuildIndexInformer cache.TypedSharedIndexInformer[*apiscamelv1.Build]

// BuildHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for Build.
type BuildHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apiscamelv1.Build]

// BuildDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for Build.
type BuildDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apiscamelv1.Build]

// BuildFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for Build.
type BuildFilteringHandler = cache.TypedFilteringResourceEventHandler[*apiscamelv1.Build]

// BuildIndexers is a specialization of [cache.TypedIndexers] for Build.
type BuildIndexers = cache.TypedIndexers[*apiscamelv1.Build]

// DeletedBuild is a specialization of [cache.DeletedObject] for Build.
type DeletedBuild = cache.DeletedObject[*apiscamelv1.Build]

type buildInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBuildInformer constructs a new informer for Build type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedBuildInformer]).
func NewBuildInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewBuildInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedBuildInformer constructs a new informer for Build type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedBuildInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers BuildIndexers) BuildIndexInformer {
	return NewTypedBuildInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredBuildInformer constructs a new informer for Build type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredBuildInformer]).
func NewFilteredBuildInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedBuildInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredBuildInformer constructs a new informer for Build type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredBuildInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers BuildIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) BuildIndexInformer {
	return NewTypedBuildInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewBuildInformerWithOptions constructs a new informer for Build type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedBuildInformerWithOptions]).
func NewBuildInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedBuildInformerWithOptions(client, namespace, options)
}

// NewTypedBuildInformerWithOptions constructs a new informer for Build type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedBuildInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) BuildIndexInformer {
	gvr := schema.GroupVersionResource{Group: "camel.apache.org", Version: "v1", Resource: "builds"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apiscamelv1.Build](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CamelV1().Builds(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CamelV1().Builds(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CamelV1().Builds(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CamelV1().Builds(namespace).Watch(ctx, opts)
			},
		}, client),
		&apiscamelv1.Build{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *buildInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedBuildInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *buildInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *buildInformer) TypedInformer() BuildIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiscamelv1.Build](f.factory.InformerFor(&apiscamelv1.Build{}, f.defaultInformer))
}

func (f *buildInformer) Lister() camelv1.BuildLister {
	return camelv1.NewBuildLister(f.Informer().GetIndexer())
}

// ToTypedBuildInformer converts an untyped informer into a TypedBuildInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Build. If that is not the case, calling type-safe methods of the returned
// TypedBuildInformer leads to runtime panics. A safer alternative is to pass
// around a TypedBuildInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedBuildInformer(informer BuildInformer) TypedBuildInformer {
	if informer, ok := informer.(TypedBuildInformer); ok {
		return informer
	}
	return &buildTypedInformerAdapter{informer}
}

type buildTypedInformerAdapter struct {
	BuildInformer
}

func (a *buildTypedInformerAdapter) TypedInformer() BuildIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiscamelv1.Build](a.Informer())
}

// ToBuildIndexInformer converts an untyped informer into a BuildIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Build. If that is not the case, calling type-safe methods of the returned
// BuildIndexInformer leads to runtime panics. A safer alternative is to pass
// around a BuildIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToBuildIndexInformer(informer cache.SharedIndexInformer) BuildIndexInformer {
	if informer, ok := informer.(BuildIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apiscamelv1.Build](informer)
}
