/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apiscamelv1 "github.com/apache/camel-k/v2/pkg/apis/camel/v1"
	versioned "github.com/apache/camel-k/v2/pkg/client/camel/clientset/versioned"
	internalinterfaces "github.com/apache/camel-k/v2/pkg/client/camel/informers/externalversions/internalinterfaces"
	camelv1 "github.com/apache/camel-k/v2/pkg/client/camel/listers/camel/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PipeInformer provides access to a shared informer and lister for
// Pipes. Prefer using the type-safe variant (see [TypedPipeInformer]).
type PipeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() camelv1.PipeLister
}

// TypedPipeInformer provides access to a shared informer and lister for
// Pipes, including the type-safe TypedInformer variant.
// It is a superset of PipeInformer.
type TypedPipeInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() PipeIndexInformer
	Lister() camelv1.PipeLister
}

// PipeIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type PipeIndexInformer cache.TypedSharedIndexInformer[*apiscamelv1.Pipe]

// PipeHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for Pipe.
type PipeHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apiscamelv1.Pipe]

// PipeDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for Pipe.
type PipeDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apiscamelv1.Pipe]

// PipeFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for Pipe.
type PipeFilteringHandler = cache.TypedFilteringResourceEventHandler[*apiscamelv1.Pipe]

// PipeIndexers is a specialization of [cache.TypedIndexers] for Pipe.
type PipeIndexers = cache.TypedIndexers[*apiscamelv1.Pipe]

// DeletedPipe is a specialization of [cache.DeletedObject] for Pipe.
type DeletedPipe = cache.DeletedObject[*apiscamelv1.Pipe]

type pipeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPipeInformer constructs a new informer for Pipe type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedPipeInformer]).
func NewPipeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewPipeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedPipeInformer constructs a new informer for Pipe type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedPipeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers PipeIndexers) PipeIndexInformer {
	return NewTypedPipeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredPipeInformer constructs a new informer for Pipe type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredPipeInformer]).
func NewFilteredPipeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedPipeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredPipeInformer constructs a new informer for Pipe type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredPipeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers PipeIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) PipeIndexInformer {
	return NewTypedPipeInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewPipeInformerWithOptions constructs a new informer for Pipe type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedPipeInformerWithOptions]).
func NewPipeInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedPipeInformerWithOptions(client, namespace, options)
}

// NewTypedPipeInformerWithOptions constructs a new informer for Pipe type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedPipeInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) PipeIndexInformer {
	gvr := schema.GroupVersionResource{Group: "camel.apache.org", Version: "v1", Resource: "pipes"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apiscamelv1.Pipe](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CamelV1().Pipes(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CamelV1().Pipes(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CamelV1().Pipes(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CamelV1().Pipes(namespace).Watch(ctx, opts)
			},
		}, client),
		&apiscamelv1.Pipe{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *pipeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedPipeInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *pipeInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *pipeInformer) TypedInformer() PipeIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiscamelv1.Pipe](f.factory.InformerFor(&apiscamelv1.Pipe{}, f.defaultInformer))
}

func (f *pipeInformer) Lister() camelv1.PipeLister {
	return camelv1.NewPipeLister(f.Informer().GetIndexer())
}

// ToTypedPipeInformer converts an untyped informer into a TypedPipeInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Pipe. If that is not the case, calling type-safe methods of the returned
// TypedPipeInformer leads to runtime panics. A safer alternative is to pass
// around a TypedPipeInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedPipeInformer(informer PipeInformer) TypedPipeInformer {
	if informer, ok := informer.(TypedPipeInformer); ok {
		return informer
	}
	return &pipeTypedInformerAdapter{informer}
}

type pipeTypedInformerAdapter struct {
	PipeInformer
}

func (a *pipeTypedInformerAdapter) TypedInformer() PipeIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apiscamelv1.Pipe](a.Informer())
}

// ToPipeIndexInformer converts an untyped informer into a PipeIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Pipe. If that is not the case, calling type-safe methods of the returned
// PipeIndexInformer leads to runtime panics. A safer alternative is to pass
// around a PipeIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToPipeIndexInformer(informer cache.SharedIndexInformer) PipeIndexInformer {
	if informer, ok := informer.(PipeIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apiscamelv1.Pipe](informer)
}
