[[integration-logging]]
= Camel K Integration Logging

Starting with https://camel.apache.org/blog/2021/05/new-camel-k-logging-features/[Camel K 1.5], we introduced a new
xref:traits:logging.adoc[logging trait] that simplifies access to the logging configuration available on the runtime.


[[integration-logging-level]]
== Logging Level

To configure the log level, pass one of the supported log levels to the trait. For example:

```
--trait logging.level=DEBUG
```


[[integration-logging-format]]
== Logging Format

The format of the logging message can also be configured using one of the supported log format options from
https://quarkus.io/guides/logging[Quarkus] (which provides the logging framework for Camel Quarkus which is leveraged by
Camel K).

A sample custom configuration would look like this:

```
--trait logging.format='%d{HH:mm:ss} %-5p (%t) %s%e%n'.
```

[[integration-logging-structured]]
== Structured Logs in Json Format

Like the operator, the integrations will use structured logs to facilitate collection and parsing. This can be turned on
or off using the `--trait logging.json` trait. Subsequently, it can also be customized to output pretty json logs by
setting the `logging.json.pretty-print` trait.