= Apache Camel K

Apache Camel K is a lightweight integration framework built from Apache Camel that runs natively on Kubernetes and is specifically designed for serverless and microservice architectures. The Camel K https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Kubernetes Operator] is in charge to transform a user provided Integration custom resource into a Camel application running on the cloud.

Users of Camel K can instantly run integration code written in any Camel DSL without worrying about the building and deployment of the application on the cloud.

[[how-it-works]]
== How It Works

Just write a _helloworld.yaml_ integration file with the following content:

[source,yaml]
----
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: helloworld
spec:
  flows:
  - from:
      steps:
      - setBody:
          simple: Hello Camel from ${routeId}
      - log: ${body}
      uri: timer:yaml
----

You can then execute the following command:

[source]
----
kubectl -f helloworld.yaml
----

The integration code will immediately run in the cloud. Continue reading the documentation to xref:installation/installation.adoc[install and get started with Camel K].

== Camel dependencies matrix
--
ifdef::lts[This is a long term service release.]
ifndef::lts[]
ifdef::prerelease[This is a development version of {page-component-title}. It should not be used in production.]
ifndef::prerelease[This release will not be updated, but rather replaced by a new release.]
endif::[]
--

From Camel K version 2 onward you will be able to use any Camel K Runtime. Each runtime depends on a Camel Quarkus, Camel and Quarkus Platform version. Every Camel K has a default runtime used, but you can xref:running/runtime-version.adoc[pick any Camel K Runtime available] (backward and forward compatible).

[caption=]
.Camel dependencies matrix
[width="100%",cols="4,2,2,2,2,2,1,3",options="header"]
|===
|Camel K Version
|(Default) Camel K Runtime
|Camel Quarkus
|Camel
|Quarkus
|Kamelets
|LTS
|Branch
|===

//cannot use top level index.adoc as the page with the query is always omitted.
indexTable::[version="*",relative="running/running.adoc",cellformats="util.ckRef(pageComponentDisplayVersion, pageComponentVersion)|camelKRuntimeVersion|util.camelQuarkusRef(camelQuarkusVersion, camelQuarkusDocsVersion)|util.camelRef(camelVersion, camelDocsVersion)|util.quarkusRef(quarkusVersion)|util.kameletsRef(camelKameletsVersion, camelKameletsDocsVersion)|lts|ck.branch(pageComponentVersion)", requires={requires},transform=util.sortCompatibilityItems]

== Other APIs version matrix

Below you can find a list of the main dependencies and APIs used by Camel K and the related compatibility.

[caption=]
.Kubernetes and other dependencies
[width="100%",cols="4,2,2,2,2,2,2",options="header"]
|===
|Camel K Version
|Kubernetes API
|Operator Framework API
|Knative API
|Service Binding Operator
|Prometheus Operator
|Kustomize version
|===

//cannot use top level index.adoc as the page with the query is always omitted.
indexTable::[version="*",relative="running/running.adoc",cellformats="util.ckRef(pageComponentDisplayVersion, pageComponentVersion)|kubernetesApiVersion|operatorFwkApiVersion|knativeApiVersion|serviceBindingOpVersion|prometheusOpVersion|kustomizeVersion", requires={requires},transform=util.sortCompatibilityItems]
