= Apache Camel K

[NOTE]
--
This version ({page-component-display-version}) of {page-component-title} depends on:

* https://github.com/apache/camel-k-runtime.git[camel-k-runtime] at version {camel-k-runtime-version}, and therefore:
** xref:{camel-quarkus-docs-version}@camel-quarkus::index.adoc[] at version {camel-quarkus-version}.
** xref:{camel-docs-version}@components::index.adoc[Camel] at version {camel-version}
** https://quarkus.io[Quarkus] at version {quarkus-version}
* xref:{camel-kamelets-docs-version}@camel-kamelets::index.adoc[] at version {camel-kamelets-version}

ifdef::lts[This is a long term service release.]
ifndef::lts[]
ifdef::prerelease[This is the development version of {page-component-title}. It should not be used in production.]
ifndef::prerelease[This release will not be updated, but rather replaced by a new release.]
endif::[]
--

Apache Camel K is a lightweight integration framework built from Apache Camel that runs natively on Kubernetes and is specifically designed for serverless and microservice architectures.

Users of Camel K can instantly run integration code written in Camel DSL on their preferred cloud (Kubernetes or OpenShift).

[[how-it-works]]
== How It Works

Just write a _helloworld.groovy_ integration file with the following content:

```groovy
from('timer:tick?period=3000')
  .setBody().constant('Hello world from Camel K')
  .to('log:info')
```

You can then execute the following command:

```
kamel run helloworld.groovy
```

The integration code immediately runs in the cloud. **Nothing else** is needed.

Continue reading the documentation to xref:installation/installation.adoc[install and get started with Camel K].

== Camel dependencies matrix

From Camel K version 2 onward you will be able to use any Camel K Runtime. Each runtime depends on a Camel Quarkus, Camel and Quarkus Platform version. Every Camel K has a default runtime used, but you can xref:running/runtime-version.adoc[pick any Camel K Runtime available] (backward and forward compatible).

[caption=]
.Camel dependencies matrix
[width="100%",cols="4,2,2,2,2,2,1,3",options="header"]
|===
|Camel K Version
|(Default) Camel K Runtime
|Camel Quarkus
|Camel
|Quarkus
|Kamelets
|LTS
|Branch
|===

== Other APIs version matrix

Below you can find a list of the main dependencies and APIs used by Camel K and the related compatibility.

[caption=]
.Kubernetes and other dependencies
[width="100%",cols="4,2,2,2,2,2,2",options="header"]
|===
|Camel K Version
|Kubernetes API
|Operator Framework API
|Knative API
|Service Binding Operator
|Prometheus Operator
|Kustomize version
|===

//cannot use top level index.adoc as the page with the query is always omitted.
indexTable::[version="*",relative="running/running.adoc",cellformats="util.ckRef(pageComponentDisplayVersion, pageComponentVersion)|kubernetesApiVersion|operatorFwkApiVersion|knativeApiVersion|serviceBindingOpVersion|prometheusOpVersion|kustomizeVersion", requires={requires},transform=util.sortCompatibilityItems]
