apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: integrationcontexts.camel.apache.org
  labels:
    app: "camel-k"
spec:
  group: camel.apache.org
  names:
    kind: IntegrationContext
    listKind: IntegrationContextList
    plural: integrationcontexts
    singular: integrationcontext
    shortNames:
    - ictx
  scope: Namespaced
  version: v1alpha1
