apiVersion: v1
kind: Service
metadata:
  labels:
    name: camel-k-operator
    app: "camel-k"
  name: camel-k-operator
spec:
  ports:
    - name: metrics
      port: 60000
      protocol: TCP
      targetPort: metrics
  selector:
    name: camel-k-operator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
