apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-k-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: camel-k-operator
  template:
    metadata:
      labels:
        name: camel-k-operator
    spec:
      containers:
        - name: camel-k-operator
          image: docker.io/apache/camel-k:0.0.1-SNAPSHOT
          command:
          - camel-k-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
