apiVersion: camel.apache.org/v1alpha1
kind: IntegrationPlatform
metadata:
  name: camel-k
  labels:
    app: "camel-k"
spec:
  build:
    camelVersion: "2.23.1"
    baseImage: "fabric8/s2i-java:3.0-java8"
    localRepository: "/tmp/artifacts/m2"
