# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------

name: automatic-updates
description: 'action used to run automation required by the project'

inputs:
  branch-ref:
    required: true
    type: string
  secretGithubToken:
    required: true
  goVersionFile:
    required: true
    type: string
  javaVersion:
    description: "Java version"
    required: true
  javaDistribution:
    description: "Java distribution"
    required: true

runs:
  using: "composite"
  steps:

    - name: Install Go ${{ inputs.goVersionFile }}
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ inputs.goVersionFile }}
        check-latest: true

    - name: Set up JDK ${{ inputs.javaVersion }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.javaDistribution }}
        java-version: ${{ inputs.javaVersion }}

    - name: Generate changelog
      uses: ./.github/actions/changelog
      with:
        token: ${{ inputs.secretGithubToken }}
        release_branch: ${{ inputs.branch-ref }}

    # Autogenerated resources
    - name: Run project refresh actions
      shell: bash
      run: |
        make generate codegen update-docs

    # Coverage badge
    - name: Run Test and get coverage badge
      shell: bash
      run: |
        go test -v ./... -covermode=count -coverprofile=coverage.out
        # Remove mock and generated code from account
        grep -v "github.com/apache/camel-k/v2/pkg/client" coverage.out \
          | grep -v "zz_generated" \
          | grep -v "github.com/apache/camel-k/v2/addons/strimzi/duck/" \
          | grep -v "github.com/apache/camel-k/v2/addons/keda/duck/" \
          | grep -v "github.com/apache/camel-k/v2/cmd/util"  > coverage.mod.out
        go tool cover -func=coverage.mod.out -o=coverage.mod.out
        grep -o -P '(?<=\(statements\))(.+)(?=%)' coverage.mod.out | xargs > coverage
        touch badge.out
        curl -sf https://gobinaries.com/github.com/AlexBeauchemin/gobadge@v0.2.0 | PREFIX=. sh
        chmod +x gobadge
        ./gobadge -filename=coverage -target=badge.out

    - name: Convert badge to adoc
      shell: bash
      run: |
        replacement=$(grep -o 'https://[^)]*' badge.out)
        target="(?:https:\/\/img\.shields\.io\/badge\/Coverage).*?(?=\.svg)"
        perl -i -pe "s|${target}|${replacement}|g" README.adoc

    # Git push
    - name: Push changes
      shell: bash
      env:
        CI_USER: "github-actions[bot]"
        CI_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
        CI_TOKEN: ${{ inputs.secretGithubToken }}
      run: |
        git config --local user.email "$CI_EMAIL"
        git config --local user.name "$CI_USER"
        git add README.adoc CHANGELOG.md && git commit -m 'chore: nightly automatic updates' || echo "No nightly automatic updates changes to commit"
        git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:${{ inputs.branch-ref }} || echo "No nightly automatic updates changes to push"

    # Give it a rest to avoid hitting Github API rate limit
    - name: Sleep
      shell: bash
      run: |
        sleep 1800
