# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------

name: kamel-config-cluster
description: 'Delegates to respective cluster action depending on type of requested platform'

inputs:
  cluster-type:
    description: 'The type of cluster required: [kind, ocp3, custom]'
    required: true
    default: 'kind'
  platform-config:
    description: 'The JSON configuration of the platform - required for custom platform type only'
    required: false

runs:
  using: "composite"
  steps:
    - name: Override platform type if there is a custom platform-config
      shell: bash
      run: |
        if [ -n "${{ inputs.platform-config }}" ]; then
          #
          # Have custom platform-config so override platform-type
          #
          echo "PLATFORM_TYPE=custom" >> $GITHUB_ENV
        else
          echo "Info: No platform configuration supplied."
          echo "PLATFORM_TYPE=${{ inputs.cluster-type }}" >> $GITHUB_ENV
        fi

    #
    # TODO
    # Due to lack of if in steps, need to use conditional action which
    # does not currently include output support so have to put all vars
    # as environment vars. When either ChristopherHX or github support allow
    # for alternative then update accordingly.
    #
    - id: execute-kind
      name: Maybe Execute Kind Cluster
      uses: ./.github/actions/conditional
      with:
        if: ${{ env.PLATFORM_TYPE == 'kind' }}
        step: |
          uses: ./.github/actions/kamel-config-cluster-kind

    - id: execute-ocp3
      name: Maybe Execute Minishift Cluster
      uses: ./.github/actions/conditional
      with:
        if: ${{ env.PLATFORM_TYPE == 'ocp3' }}
        step: |
          uses: ./.github/actions/kamel-config-cluster-ocp3

    - id: execute-custom
      name: Maybe Execute Custom Cluster
      uses: ./.github/actions/conditional
      env:
        PLATFORM_CONFIG_DATA: ${{ inputs.platform-config }}
      with:
        if: ${{ env.PLATFORM_TYPE == 'custom' }}
        step: |
          uses: ./.github/actions/kamel-config-cluster-custom

    - id: execute-invalid
      name: Execute Invalid Cluster
      uses: ./.github/actions/conditional
      with:
        if: ${{ env.PLATFORM_TYPE != 'kind' &&  env.PLATFORM_TYPE != 'ocp3' &&  env.PLATFORM_TYPE != 'custom' }}
        step: |
          shell: bash
          run: |
            echo "Error: Unrecognised platform request for type of cluster. Should be kind, ocp3 or custom."
            exit 1

    - id: platform-info
      shell: bash
      env:
        DEFAULT_IMAGE_NAMESPACE: 'apache'
      run: |
        echo "::set-output name=image-registry-push-host::$(echo ${{ env.IMAGE_REGISTRY_PUSH_HOST }})"
        echo "::set-output name=image-registry-pull-host::$(echo ${{ env.IMAGE_REGISTRY_PULL_HOST }})"
        echo "::set-output name=image-registry-insecure::$(echo ${{ env.IMAGE_REGISTRY_INSECURE }})"
        echo "::set-output name=kube-admin-user-ctx::$(echo ${{ env.KUBE_ADMIN_USER_CTX }})"
        echo "::set-output name=kube-user-ctx::$(echo ${{ env.KUBE_USER_CTX }})"
        echo "::set-output name=install-olm::$(echo ${{ env.INSTALL_OLM }})"

        if [ -n "${{ env.IMAGE_NAMESPACE }}" ]; then
          echo "::set-output name=image-namespace::$(echo ${{ env.IMAGE_NAMESPACE }})"
        else
          echo "::set-output name=image-namespace::$(echo ${{ env.DEFAULT_IMAGE_NAMESPACE }})"
        fi

        #
        # Clear out environment variables
        #
        echo "TEST_PLATFORM_CLUSTER=" >> $GITHUB_ENV
        echo "IMAGE_REGISTRY_PUSH_HOST=" >> $GITHUB_ENV
        echo "IMAGE_REGISTRY_PULL_HOST=" >> $GITHUB_ENV
        echo "IMAGE_REGISTRY_INSECURE=" >> $GITHUB_ENV
        echo "KUBE_ADMIN_USER_CTX=" >> $GITHUB_ENV
        echo "KUBE_USER_CTX=" >> $GITHUB_ENV
        echo "INSTALL_OLM=" >> $GITHUB_ENV
        echo "IMAGE_NAMESPACE=" >> $GITHUB_ENV
        echo "DEFAULT_IMAGE_NAMESPACE=" >> $GITHUB_ENV

      #
      # Install opm if required
      #
    - id: install-opm
      name: Install opm if required
      shell: bash
      run: |
        if [ "${{ inputs.opm }}" == "true" ]; then
          curl -L https://github.com/operator-framework/operator-registry/releases/download/v1.19.5/linux-amd64-opm -o opm
          chmod +x opm
          sudo mv opm /usr/local/bin/
        fi

      #
      # Install OLM if required
      #
    - id: install-olm
      name: Install OLM
      shell: bash
      run: |
        if [ "${{ steps.platform-info.outputs.install-olm }}" == "false" ]; then
          # OLM explicitly not required - installed by default
          echo "OLM install not required for this cluster"
          exit 0
        fi

        #
        # Get current context
        #
        echo "Cache current kube context"
        ctx=$(kubectl config current-context)

        #
        # Need to be admin so switch to the admin context
        #
        echo "Change to kube admin context"
        kubectl config use-context "${{ steps.platform-info.outputs.kube-admin-user-ctx }}"

        set +e
        echo "Check if OLM is already installed"
        kubectl get deployments --all-namespaces | grep olm-operator
        if [ $? != 0 ]; then
          set -e
          echo "OLM not detected on cluster so downloading and installing"
          kubectl apply -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.17.0/crds.yaml
          # wait for a while to be sure CRDs are installed
          sleep 1
          kubectl apply -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.17.0/olm.yaml
        fi
        set -e

        #
        # Change back to original context
        #
        echo "Return to original kube context"
        kubectl config use-context "${ctx}"

        echo "Complete"

outputs:
  image-registry-push-host:
    description: "Registry for storing images host push interface"
    value: ${{ steps.platform-info.outputs.image-registry-push-host }}
  image-registry-pull-host:
    description: "Registry for storing images host pull interface"
    value: ${{ steps.platform-info.outputs.image-registry-pull-host }}
  image-registry-insecure:
    description: "Whether the image registry requires secure/authenticated access"
    value: ${{ steps.platform-info.outputs.image-registry-insecure }}
  image-namespace:
    description: "Registry namespace for storing images"
    value: ${{ steps.platform-info.outputs.image-namespace }}
  kube-admin-user-ctx:
    description: "The admin user context of the cluster"
    value: ${{ steps.platform-info.outputs.kube-admin-user-ctx }}
  kube-user-ctx:
    description: "The user context of the cluster"
    value: ${{ steps.platform-info.outputs.kube-user-ctx }}
