---
apiVersion: v1
data:
  my-file.txt: hello
kind: ConfigMap
metadata:
  name: my-cm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-camel-sb-svc
  name: my-camel-sb-svc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-camel-sb-svc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-camel-sb-svc
    spec:
      containers:
      - image: docker.io/squakez/my-camel-sb-svc:1.0.0
        imagePullPolicy: IfNotPresent
        name: my-camel-sb-svc
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: my-cm
          mountPath: /tmp/app/data
      volumes:
      - name: my-cm
        configMap:
          name: my-cm
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
