/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	strimziv1 "github.com/apache/camel-k/v2/pkg/apis/duck/strimzi/v1"
	scheme "github.com/apache/camel-k/v2/pkg/client/strimzi/clientset/internalclientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KafkaTopicsGetter has a method to return a KafkaTopicInterface.
// A group's client should implement this interface.
type KafkaTopicsGetter interface {
	KafkaTopics(namespace string) KafkaTopicInterface
}

// KafkaTopicInterface has methods to work with KafkaTopic resources.
type KafkaTopicInterface interface {
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*strimziv1.KafkaTopic, error)
	List(ctx context.Context, opts metav1.ListOptions) (*strimziv1.KafkaTopicList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	KafkaTopicExpansion
}

// kafkaTopics implements KafkaTopicInterface
type kafkaTopics struct {
	*gentype.ClientWithList[*strimziv1.KafkaTopic, *strimziv1.KafkaTopicList]
}

// newKafkaTopics returns a KafkaTopics
func newKafkaTopics(c *KafkaV1Client, namespace string) *kafkaTopics {
	return &kafkaTopics{
		gentype.NewClientWithList[*strimziv1.KafkaTopic, *strimziv1.KafkaTopicList](
			"kafkatopics",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *strimziv1.KafkaTopic { return &strimziv1.KafkaTopic{} },
			func() *strimziv1.KafkaTopicList { return &strimziv1.KafkaTopicList{} },
		),
	}
}
