/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	strimziv1 "github.com/apache/camel-k/v2/pkg/apis/duck/strimzi/v1"
	scheme "github.com/apache/camel-k/v2/pkg/client/strimzi/clientset/internalclientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KafkasGetter has a method to return a KafkaInterface.
// A group's client should implement this interface.
type KafkasGetter interface {
	Kafkas(namespace string) KafkaInterface
}

// KafkaInterface has methods to work with Kafka resources.
type KafkaInterface interface {
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*strimziv1.Kafka, error)
	List(ctx context.Context, opts metav1.ListOptions) (*strimziv1.KafkaList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	KafkaExpansion
}

// kafkas implements KafkaInterface
type kafkas struct {
	*gentype.ClientWithList[*strimziv1.Kafka, *strimziv1.KafkaList]
}

// newKafkas returns a Kafkas
func newKafkas(c *KafkaV1Client, namespace string) *kafkas {
	return &kafkas{
		gentype.NewClientWithList[*strimziv1.Kafka, *strimziv1.KafkaList](
			"kafkas",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *strimziv1.Kafka { return &strimziv1.Kafka{} },
			func() *strimziv1.KafkaList { return &strimziv1.KafkaList{} },
		),
	}
}
