apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: timer
spec:
  definition:
    title: "Timer"
    description: "Produces produces periodic events with a custom payload"
    required:
      - message
    properties:
      message:
        title: Message
        description: The message to generate
        type: string
  types:
    out:
      mediaType: application/json
      schema:
        id: text.camel.apache.org
        type: string
  flow:
    from:
      uri: timer:tick
      steps:
        - set-body:
            constant: "Hello [here there'll be the message] !!!"
        - to: "log:info"
