apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: integrations.camel.apache.org
  labels:
    app: "camel-k"
spec:
  group: camel.apache.org
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  names:
    kind: Integration
    listKind: IntegrationList
    plural: integrations
    singular: integration
    shortNames:
    - it
  additionalPrinterColumns:
    - name: Phase
      type: string
      description: The Integration phase
      JSONPath: .status.phase
    - name: Context
      type: string
      description: The IntegrationContext to use
      JSONPath: .status.context
