apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: keda-kafka-auto-discovery
  namespace: kafka
spec:
  sources:
    - content: |
        from("kafka:my-topic?brokers=my-cluster-kafka-bootstrap.kafka.svc:9092&groupId=auto-group")
          .log("${body}");
      name: routes.java
  traits:
    keda:
      enabled: true
      minReplicaCount: 0
      maxReplicaCount: 1
      # No triggers - auto-discovery should create kafka scaler