# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: ibm-mq
type: Opaque
# password: ibmmqpasswd
data:
  ibm-mq-password: aWJtbXFwYXNzd2Q=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-mq-server
  labels:
    app: ibm-mq-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibm-mq-server
  template:
    metadata:
      labels:
        app: ibm-mq-server
    spec:
      containers:
        - name: ibm-mq-server
          image: ibmcom/mq
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 1414
            - containerPort: 9443
          env:
            - name: LICENSE
              value: "accept"
            - name:  MQ_QMGR_NAME
              value: "QM1"
            - name:  MQ_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ibm-mq
                  key: ibm-mq-password

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ibm-mq-server
  name: ibm-mq-server
spec:
  ports:
  - name: port-1
    port: 1414
    protocol: TCP
    targetPort: 1414
  - name: port-2
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    app: ibm-mq-server
  type: ClusterIP
