apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: steps-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: timer-source
    properties:
      message: "Camel"
  steps:
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: prefix-action
    properties:
      prefix: "Apache"
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: prefix-action
    properties:
      prefix: "Hello"
  sink:
    uri: log:info
