[[configuring-registry-github]]
= Configuring a Github Packages Registry

You can use a Github Packages registry to host your container images, in case your cluster doesn't provide a xref:installation/registry/registry.adoc[default registry].

Login to Github, then navigate to `Settings -> Developer settings -> Personal access tokens`.
Create a new token with the following permissions:

* `repo` (all)
* `write:packages`
* `read:packages`
* `delete:packages`

Take note of the personal access token, you'll use it during installation. You also need to **choose a github repository** for hosting your images.

To configure Camel K, install it using the following command:

[source,bash]
----
kamel install --registry docker.pkg.github.com --organization github-user/repository --registry-auth-username github-user-id --registry-auth-password github-token
----

The `--registry-auth-username` and `--registry-auth-password` flags are used by the `kamel` CLI to create a Kubernetes secret
that holds your credentials for authenticating against the Docker registry.

In the general case, the `--registry-auth-server` should be used, but it can be omitted for Github because it's
equal to the registry by default (`docker.pkg.github.com`).

You're now ready to publish your integration. Images will be automatically published to Github Packages.
