apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: integrationcontexts.camel.apache.org
  labels:
    app: "camel-k"
spec:
  group: camel.apache.org
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  names:
    kind: IntegrationContext
    listKind: IntegrationContextList
    plural: integrationcontexts
    singular: integrationcontext
    shortNames:
    - ictx
  additionalPrinterColumns:
    - name: Phase
      type: string
      description: The IntegrationContext phase
      JSONPath: .status.phase
    - name: Type
      type: string
      description: The IntegrationContext type
      JSONPath: .metadata.labels.camel\.apache\.org\/context\.type
    - name: Image
      type: string
      description: The IntegrationContext image
      JSONPath: .status.image
