= Camel dependencies matrix

[caption=]
.Camel dependencies matrix
[width="100%",cols="4,2,2,2,2,3",options="header"]
|===
|Camel K Version
|Last release
|Default Quarkus Platform
|Camel Quarkus
|Camel
|Branch
|===

//cannot use top level index.adoc as the page with the query is always omitted.
indexTable::[version="*",relative="running/running.adoc",cellformats="util.ckRef(pageComponentDisplayVersion, pageComponentVersion)|lastReleasedVersion|quarkusVersion|camelQuarkusVersion|camelVersion|ck.branch(pageComponentVersion)", requires={requires},transform=util.sortCompatibilityItems]

NOTE: you can use any available Camel Quarkus runtime version. Alternatively you can also build any other Camel runtimes building from a Git hosted repository.

== Other APIs version matrix

Below you can find a list of the main dependencies and APIs used by Camel K and the related compatibility.

[caption=]
.Kubernetes and other dependencies
[width="100%",cols="4,2,2,2,2,2",options="header"]
|===
|Camel K Version
|Kubernetes API
|Operator Framework API
|Knative API
|Prometheus Operator
|Kustomize version
|===

//cannot use top level index.adoc as the page with the query is always omitted.
indexTable::[version="*",relative="running/running.adoc",cellformats="util.ckRef(pageComponentDisplayVersion, pageComponentVersion)|kubernetesApiVersion|operatorFwkApiVersion|knativeApiVersion|prometheusOpVersion|kustomizeVersion", requires={requires},transform=util.sortCompatibilityItems]

