---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: camel-k-tekton
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: camel-k-integrations
rules:
- apiGroups:
  - camel.apache.org
  resources:
  - integrations
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - camel.apache.org
  resources:
  - camelcatalogs
  verbs:
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: camel-k-tekton-integrations
subjects:
- kind: ServiceAccount
  name: camel-k-tekton
roleRef:
  kind: Role
  name: camel-k-integrations
  apiGroup: rbac.authorization.k8s.io