apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: logger-sink-binding
spec:
  source:
    ref:
      kind: InMemoryChannel
      apiVersion: messaging.knative.dev/v1beta1
      name: messages
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: logger-sink
