apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: timer-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: timer-source
    properties:
      message: Hello Kamelets
      period: 1000
  sink:
    ref:
      kind: InMemoryChannel
      apiVersion: messaging.knative.dev/v1beta1
      name: messages
