# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------

name: registry-setting
description: 'Setting registry'

runs:
  using: "composite"

  steps:
  - id: registry-settings
    name: Create an auth secured registry
    shell: bash
    run: |
      kubectl create ns registry
      kubectl apply -f .github/actions/registry-setting/registry.yaml -n registry
      kubectl wait --for=condition=available deployment/registry -n registry --timeout=60s
      KAMEL_INSTALL_REGISTRY="$(kubectl -n registry get service registry -o jsonpath='{.spec.clusterIP}')"
      echo "KAMEL_INSTALL_REGISTRY=$KAMEL_INSTALL_REGISTRY" >> "$GITHUB_ENV"
      echo "Setting registry as $KAMEL_INSTALL_REGISTRY which is required by certain tests"
      kubectl create secret docker-registry my-registry \
        --docker-server $KAMEL_INSTALL_REGISTRY \
        --docker-username admin \
        --docker-password password \
        -n camel-k
      kubectl create configmap camel-k-operator-configmap-configuration \
        --from-literal=REGISTRY_ADDRESS="$KAMEL_INSTALL_REGISTRY" \
        --from-literal=REGISTRY_INSECURE="true" \
        --from-literal=REGISTRY_SECRET="my-registry" \
        --from-literal=MAVEN_REPOSITORIES_ALLOWED="https://maven.repository.redhat.com/ga@id=redhat" \
        -n camel-k
      E2E_TEST_REGISTRY_SECRET_COPY=true
      echo "E2E_TEST_REGISTRY_SECRET_COPY=$E2E_TEST_REGISTRY_SECRET_COPY" >> $GITHUB_ENV
      echo "Setting E2E_TEST_REGISTRY_SECRET_COPY=true in order to automate the copy of the pull secret and the setting in each test"
